### ISSUE TITLE
UI - show space errors

### ISSUE THREAD

**Issue by jonatan-kruse** [ErikLundb3rg/typebout#46]
## Problem
Right now the game shows the letter green when you have typed a letter correct and red when they are typed incorrect.
This is nice so that a player can see if they have typed the letter correctly. The problem is that spaces are not green or read so a player gets no feedback when a space is incorrecly typed.

## Example
![image](https://user-images.githubusercontent.com/42937653/235672494-1e4451e0-50a9-4a52-971d-a566b6625d79.png)

## Solution
One way to give the player this feedback would be to underline the incorrectly typed space with a red bar.

**Comment by ErikLundb3rg** [comment]
Should we really do an underline or should we highlight the background of the words like in typeracer? Or we could also have that we only highlight if it is a space error, and otherwise letters.

**Comment by jonatan-kruse** [comment]
Yes I agree that nu underlines generally but underline if there is and error
