### ISSUE TITLE
🐛 Not showing correct stats on profile

### ISSUE THREAD

**Issue by jonatan-kruse** [ErikLundb3rg/typebout#50]
## Description
wen opening my profile page I realised that the stats shown cannot be correct

## Possible cause 
I think this might have to do with the play again feature and that the stats may not work with the feature

## Image
I have definitely typed faster than 42 wpm
![image](https://user-images.githubusercontent.com/42937653/236647156-af513434-8ac1-4223-a946-27c60ef4ce59.png)

**Comment by ErikLundb3rg** [comment]
You're right, thought it could be from previously a bug in the saving of a users game stats which was triggered every time a user finished.
